# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- bash: |
    if [ -f Maven pom.xml ]; then
      echo "##vso[task.setVariable variable=FILEEXISTS]true"
    fi
- task: Maven@3
displayName: Maven pom.xml
condition: eq(variables.FILEEXISTS,'true')
inputs:
mavenPOMfile: (Buildparameters.mavenPOMfile)
options: -Djacoco.percentage.instructions = 0

- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Azure subscription 1(941e3b5d-f4c0-4f20-9474-b94bf83d7d19)'
    appType: 'functionApp'
    appName: 'hello-function-240827160520'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
